/*
 * Sample/demo data for the Boston Sports Tracker.
 * This app does not have a live sports-data API connected, so every
 * number below is illustrative placeholder data, not real results.
 * Swap TEAMS[...] fields for a live API feed (e.g. ESPN, SportsRadar,
 * MLB Stats API, balldontlie) to make this a real-time tracker —
 * the UI only depends on the shapes defined here.
 */

const TEAMS = {
  patriots: {
    name: "New England Patriots",
    league: "NFL",
    color: "#0a2342",
    accent: "#c8102e",
    logoText: "NE",
    blurb: "AFC East · Gillette Stadium, Foxborough, MA",
    scores: [
      { date: "2026-08-08", opponent: "Washington Commanders", home: true, result: "W", teamScore: 24, oppScore: 17, note: "Preseason Week 1" },
      { date: "2026-08-15", opponent: "Minnesota Vikings", home: false, result: "L", teamScore: 13, oppScore: 20, note: "Preseason Week 2" },
      { date: "2026-08-22", opponent: "New York Giants", home: true, result: "W", teamScore: 27, oppScore: 21, note: "Preseason Week 3" },
    ],
    schedule: [
      { date: "2026-09-07", opponent: "Las Vegas Raiders", home: true, time: "1:00 PM" },
      { date: "2026-09-14", opponent: "Miami Dolphins", home: false, time: "1:00 PM" },
      { date: "2026-09-21", opponent: "Pittsburgh Steelers", home: true, time: "1:00 PM" },
      { date: "2026-09-28", opponent: "San Francisco 49ers", home: false, time: "4:25 PM" },
      { date: "2026-10-05", opponent: "Buffalo Bills", home: true, time: "8:20 PM" },
      { date: "2026-10-12", opponent: "New Orleans Saints", home: false, time: "1:00 PM" },
    ],
    standings: {
      group: "AFC East",
      rows: [
        { team: "Buffalo Bills", w: 13, l: 4, pct: ".765", gb: "-" },
        { team: "New England Patriots", w: 11, l: 6, pct: ".647", gb: "2.0" },
        { team: "Miami Dolphins", w: 8, l: 9, pct: ".471", gb: "5.0" },
        { team: "New York Jets", w: 5, l: 12, pct: ".294", gb: "8.0" },
      ],
      note: "Final 2025 regular-season standings (most recent completed NFL season)",
    },
    players: [
      { name: "Drake Maye", pos: "QB", statLine: "3,912 yds · 27 TD · 9 INT · 64.8% comp" },
      { name: "Rhamondre Stevenson", pos: "RB", statLine: "1,048 rush yds · 8 TD · 4.4 YPC" },
      { name: "DeMario Douglas", pos: "WR", statLine: "78 rec · 921 yds · 6 TD" },
      { name: "Hunter Henry", pos: "TE", statLine: "62 rec · 704 yds · 7 TD" },
      { name: "Christian Gonzalez", pos: "CB", statLine: "4 INT · 16 PD · 68 tkl" },
      { name: "Matthew Judon", pos: "EDGE", statLine: "10.5 sacks · 38 tkl · 3 FF" },
    ],
    historySource: { label: "Pro Football Reference — Patriots franchise history", url: "https://www.pro-football-reference.com/teams/nwe/" },
    history: [
      { year: 2025, lg: "NFL", team: "New England Patriots", w: 14, l: 3, t: 0, finish: "1st of 4", playoffs: "", pf: 490, pa: 320, diff: 170, coach: "Vrabel", passer: "Maye", rusher: "Henderson", receiver: "Diggs", srs: 5.5 },
      { year: 2024, lg: "NFL", team: "New England Patriots", w: 4, l: 13, t: 0, finish: "4th of 4", playoffs: "", pf: 289, pa: 417, diff: -128, coach: "Mayo", passer: "Maye", rusher: "Stevenson", receiver: "Henry", srs: -8.1 },
      { year: 2023, lg: "NFL", team: "New England Patriots", w: 4, l: 13, t: 0, finish: "4th of 4", playoffs: "", pf: 236, pa: 366, diff: -130, coach: "Belichick", passer: "Jones", rusher: "Elliott", receiver: "Douglas", srs: -7.9 },
      { year: 2022, lg: "NFL", team: "New England Patriots", w: 8, l: 9, t: 0, finish: "3rd of 4", playoffs: "", pf: 364, pa: 347, diff: 17, coach: "Belichick", passer: "Jones", rusher: "Stevenson", receiver: "Meyers", srs: 2.0 },
      { year: 2021, lg: "NFL", team: "New England Patriots", w: 10, l: 7, t: 0, finish: "2nd of 4", playoffs: "Lost WC", pf: 462, pa: 303, diff: 159, coach: "Belichick", passer: "Jones", rusher: "Harris", receiver: "Meyers", srs: 8.5 },
      { year: 2020, lg: "NFL", team: "New England Patriots", w: 7, l: 9, t: 0, finish: "3rd of 4", playoffs: "", pf: 326, pa: 353, diff: -27, coach: "Belichick", passer: "Newton", rusher: "Harris", receiver: "Meyers", srs: -1.0 },
      { year: 2019, lg: "NFL", team: "New England Patriots", w: 12, l: 4, t: 0, finish: "1st of 4", playoffs: "Lost WC", pf: 420, pa: 225, diff: 195, coach: "Belichick", passer: "Brady", rusher: "Michel", receiver: "Edelman", srs: 10.4 },
      { year: 2018, lg: "NFL", team: "New England Patriots", w: 11, l: 5, t: 0, finish: "1st of 4", playoffs: "Won SB", pf: 436, pa: 325, diff: 111, coach: "Belichick", passer: "Brady", rusher: "Michel", receiver: "Edelman", srs: 5.2 },
      { year: 2017, lg: "NFL", team: "New England Patriots", w: 13, l: 3, t: 0, finish: "1st of 4", playoffs: "Lost SB", pf: 458, pa: 296, diff: 162, coach: "Belichick", passer: "Brady", rusher: "Lewis", receiver: "Gronkowski", srs: 8.9 },
      { year: 2016, lg: "NFL", team: "New England Patriots", w: 14, l: 2, t: 0, finish: "1st of 4", playoffs: "Won SB", pf: 441, pa: 250, diff: 191, coach: "Belichick", passer: "Brady", rusher: "Blount", receiver: "Edelman", srs: 9.3 },
      { year: 2015, lg: "NFL", team: "New England Patriots", w: 12, l: 4, t: 0, finish: "1st of 4", playoffs: "Lost Conf", pf: 465, pa: 315, diff: 150, coach: "Belichick", passer: "Brady", rusher: "Blount", receiver: "Gronkowski", srs: 7.0 },
      { year: 2014, lg: "NFL", team: "New England Patriots", w: 12, l: 4, t: 0, finish: "1st of 4", playoffs: "Won SB", pf: 468, pa: 313, diff: 155, coach: "Belichick", passer: "Brady", rusher: "Gray", receiver: "Gronkowski", srs: 10.9 },
      { year: 2013, lg: "NFL", team: "New England Patriots", w: 12, l: 4, t: 0, finish: "1st of 4", playoffs: "Lost Conf", pf: 444, pa: 338, diff: 106, coach: "Belichick", passer: "Brady", rusher: "Ridley", receiver: "Edelman", srs: 5.9 },
      { year: 2012, lg: "NFL", team: "New England Patriots", w: 12, l: 4, t: 0, finish: "1st of 4", playoffs: "Lost Conf", pf: 557, pa: 331, diff: 226, coach: "Belichick", passer: "Brady", rusher: "Ridley", receiver: "Welker", srs: 12.8 },
      { year: 2011, lg: "NFL", team: "New England Patriots", w: 13, l: 3, t: 0, finish: "1st of 4", playoffs: "Lost SB", pf: 513, pa: 342, diff: 171, coach: "Belichick", passer: "Brady", rusher: "Green-Ellis", receiver: "Welker", srs: 9.3 },
      { year: 2010, lg: "NFL", team: "New England Patriots", w: 14, l: 2, t: 0, finish: "1st of 4", playoffs: "Lost Div", pf: 518, pa: 313, diff: 205, coach: "Belichick", passer: "Brady", rusher: "Green-Ellis", receiver: "Welker", srs: 15.4 },
      { year: 2009, lg: "NFL", team: "New England Patriots", w: 10, l: 6, t: 0, finish: "1st of 4", playoffs: "Lost WC", pf: 427, pa: 285, diff: 142, coach: "Belichick", passer: "Brady", rusher: "Maroney", receiver: "Welker", srs: 11.2 },
      { year: 2008, lg: "NFL", team: "New England Patriots", w: 11, l: 5, t: 0, finish: "2nd of 4", playoffs: "", pf: 410, pa: 309, diff: 101, coach: "Belichick", passer: "Cassel", rusher: "Morris", receiver: "Welker", srs: 3.9 },
      { year: 2007, lg: "NFL", team: "New England Patriots", w: 16, l: 0, t: 0, finish: "1st of 4", playoffs: "Lost SB", pf: 589, pa: 274, diff: 315, coach: "Belichick", passer: "Brady", rusher: "Maroney", receiver: "Moss", srs: 20.1 },
      { year: 2006, lg: "NFL", team: "New England Patriots", w: 12, l: 4, t: 0, finish: "1st of 4", playoffs: "Lost Conf", pf: 385, pa: 237, diff: 148, coach: "Belichick", passer: "Brady", rusher: "Dillon", receiver: "Caldwell", srs: 10.2 },
      { year: 2005, lg: "NFL", team: "New England Patriots", w: 10, l: 6, t: 0, finish: "1st of 4", playoffs: "Lost Div", pf: 379, pa: 338, diff: 41, coach: "Belichick", passer: "Brady", rusher: "Dillon", receiver: "Branch", srs: 3.1 },
      { year: 2004, lg: "NFL", team: "New England Patriots", w: 14, l: 2, t: 0, finish: "1st of 4", playoffs: "Won SB", pf: 437, pa: 260, diff: 177, coach: "Belichick", passer: "Brady", rusher: "Dillon", receiver: "Givens", srs: 12.8 },
      { year: 2003, lg: "NFL", team: "New England Patriots", w: 14, l: 2, t: 0, finish: "1st of 4", playoffs: "Won SB", pf: 348, pa: 238, diff: 110, coach: "Belichick", passer: "Brady", rusher: "Smith", receiver: "Branch", srs: 6.9 },
      { year: 2002, lg: "NFL", team: "New England Patriots", w: 9, l: 7, t: 0, finish: "2nd of 4", playoffs: "", pf: 381, pa: 346, diff: 35, coach: "Belichick", passer: "Brady", rusher: "Smith", receiver: "Brown", srs: 4.0 },
      { year: 2001, lg: "NFL", team: "New England Patriots", w: 11, l: 5, t: 0, finish: "1st of 5", playoffs: "Won SB", pf: 371, pa: 272, diff: 99, coach: "Belichick", passer: "Brady", rusher: "Smith", receiver: "Brown", srs: 4.3 },
      { year: 2000, lg: "NFL", team: "New England Patriots", w: 5, l: 11, t: 0, finish: "5th of 5", playoffs: "", pf: 276, pa: 338, diff: -62, coach: "Belichick", passer: "Bledsoe", rusher: "Faulk", receiver: "Glenn", srs: -2.5 },
      { year: 1999, lg: "NFL", team: "New England Patriots", w: 8, l: 8, t: 0, finish: "5th of 5", playoffs: "", pf: 299, pa: 284, diff: 15, coach: "Carroll", passer: "Bledsoe", rusher: "Allen", receiver: "Glenn", srs: 2.2 },
      { year: 1998, lg: "NFL", team: "New England Patriots", w: 9, l: 7, t: 0, finish: "4th of 5", playoffs: "Lost WC", pf: 337, pa: 329, diff: 8, coach: "Carroll", passer: "Bledsoe", rusher: "Edwards", receiver: "Glenn", srs: 3.9 },
      { year: 1997, lg: "NFL", team: "New England Patriots", w: 10, l: 6, t: 0, finish: "1st of 5", playoffs: "Lost Div", pf: 369, pa: 289, diff: 80, coach: "Carroll", passer: "Bledsoe", rusher: "Martin", receiver: "Jefferson", srs: 5.3 },
      { year: 1996, lg: "NFL", team: "New England Patriots", w: 11, l: 5, t: 0, finish: "1st of 5", playoffs: "Lost SB", pf: 418, pa: 313, diff: 105, coach: "Parcells", passer: "Bledsoe", rusher: "Martin", receiver: "Glenn", srs: 5.1 },
      { year: 1995, lg: "NFL", team: "New England Patriots", w: 6, l: 10, t: 0, finish: "4th of 5", playoffs: "", pf: 294, pa: 377, diff: -83, coach: "Parcells", passer: "Bledsoe", rusher: "Martin", receiver: "Brisby", srs: -5.4 },
      { year: 1994, lg: "NFL", team: "New England Patriots", w: 10, l: 6, t: 0, finish: "2nd of 5", playoffs: "Lost WC", pf: 351, pa: 312, diff: 39, coach: "Parcells", passer: "Bledsoe", rusher: "Butts", receiver: "Coates", srs: 3.2 },
      { year: 1993, lg: "NFL", team: "New England Patriots", w: 5, l: 11, t: 0, finish: "4th of 5", playoffs: "", pf: 238, pa: 286, diff: -48, coach: "Parcells", passer: "Bledsoe", rusher: "Russell", receiver: "Coates", srs: -3.8 },
      { year: 1992, lg: "NFL", team: "New England Patriots", w: 2, l: 14, t: 0, finish: "5th of 5", playoffs: "", pf: 205, pa: 363, diff: -158, coach: "MacPherson", passer: "Millen", rusher: "Vaughn", receiver: "Fryar", srs: -11.0 },
      { year: 1991, lg: "NFL", team: "New England Patriots", w: 6, l: 10, t: 0, finish: "4th of 5", playoffs: "", pf: 211, pa: 305, diff: -94, coach: "MacPherson", passer: "Millen", rusher: "Russell", receiver: "Fryar", srs: -8.7 },
      { year: 1990, lg: "NFL", team: "New England Patriots", w: 1, l: 15, t: 0, finish: "5th of 5", playoffs: "", pf: 181, pa: 446, diff: -265, coach: "Rust", passer: "Wilson", rusher: "Stephens", receiver: "Fryar", srs: -14.6 },
      { year: 1989, lg: "NFL", team: "New England Patriots", w: 5, l: 11, t: 0, finish: "4th of 5", playoffs: "", pf: 297, pa: 391, diff: -94, coach: "Berry", passer: "Grogan", rusher: "Stephens", receiver: "Dykes", srs: -7.0 },
      { year: 1988, lg: "NFL", team: "New England Patriots", w: 9, l: 7, t: 0, finish: "3rd of 5", playoffs: "", pf: 250, pa: 284, diff: -34, coach: "Berry", passer: "Flutie", rusher: "Stephens", receiver: "Morgan", srs: -0.2 },
      { year: 1987, lg: "NFL", team: "New England Patriots", w: 8, l: 7, t: 0, finish: "2nd of 5", playoffs: "", pf: 320, pa: 293, diff: 27, coach: "Berry", passer: "Grogan", rusher: "Collins", receiver: "Morgan", srs: 3.1 },
      { year: 1986, lg: "NFL", team: "New England Patriots", w: 11, l: 5, t: 0, finish: "1st of 5", playoffs: "Lost Div", pf: 412, pa: 307, diff: 105, coach: "Berry", passer: "Eason", rusher: "James", receiver: "Morgan", srs: 5.7 },
      { year: 1985, lg: "NFL", team: "New England Patriots", w: 11, l: 5, t: 0, finish: "3rd of 5", playoffs: "Lost SB", pf: 362, pa: 290, diff: 72, coach: "Berry", passer: "Eason", rusher: "James", receiver: "Morgan", srs: 5.8 },
      { year: 1984, lg: "NFL", team: "New England Patriots", w: 9, l: 7, t: 0, finish: "2nd of 5", playoffs: "", pf: 362, pa: 352, diff: 10, coach: "Meyer,Berry", passer: "Eason", rusher: "James", receiver: "Ramsey", srs: -0.1 },
      { year: 1983, lg: "NFL", team: "New England Patriots", w: 8, l: 8, t: 0, finish: "2nd of 5", playoffs: "", pf: 274, pa: 289, diff: -15, coach: "Meyer", passer: "Grogan", rusher: "Collins", receiver: "Morgan", srs: -1.0 },
      { year: 1982, lg: "NFL", team: "New England Patriots", w: 5, l: 4, t: 0, finish: "3rd of 5", playoffs: "Lost WC", pf: 143, pa: 157, diff: -14, coach: "Meyer", passer: "Grogan", rusher: "Collins", receiver: "Morgan", srs: -2.4 },
      { year: 1981, lg: "NFL", team: "New England Patriots", w: 2, l: 14, t: 0, finish: "5th of 5", playoffs: "", pf: 322, pa: 370, diff: -48, coach: "Erhardt", passer: "Grogan", rusher: "Collins", receiver: "Morgan", srs: -3.7 },
      { year: 1980, lg: "NFL", team: "New England Patriots", w: 10, l: 6, t: 0, finish: "2nd of 5", playoffs: "", pf: 441, pa: 325, diff: 116, coach: "Erhardt", passer: "Grogan", rusher: "Ferguson", receiver: "Morgan", srs: 6.5 },
      { year: 1979, lg: "NFL", team: "New England Patriots", w: 9, l: 7, t: 0, finish: "2nd of 5", playoffs: "", pf: 411, pa: 326, diff: 85, coach: "Erhardt", passer: "Grogan", rusher: "Cunningham", receiver: "Jackson", srs: 5.1 },
      { year: 1978, lg: "NFL", team: "New England Patriots", w: 11, l: 5, t: 0, finish: "1st of 5", playoffs: "Lost Div", pf: 358, pa: 286, diff: 72, coach: "Fairbanks,Erhardt,Bullough", passer: "Grogan", rusher: "Cunningham", receiver: "Morgan", srs: 5.0 },
      { year: 1977, lg: "NFL", team: "New England Patriots", w: 9, l: 5, t: 0, finish: "3rd of 5", playoffs: "", pf: 278, pa: 217, diff: 61, coach: "Fairbanks", passer: "Grogan", rusher: "Cunningham", receiver: "Stingley", srs: 4.0 },
      { year: 1976, lg: "NFL", team: "New England Patriots", w: 11, l: 3, t: 0, finish: "2nd of 5", playoffs: "Lost Div", pf: 376, pa: 236, diff: 140, coach: "Fairbanks", passer: "Grogan", rusher: "Cunningham", receiver: "Stingley", srs: 8.6 },
      { year: 1975, lg: "NFL", team: "New England Patriots", w: 3, l: 11, t: 0, finish: "5th of 5", playoffs: "", pf: 258, pa: 358, diff: -100, coach: "Fairbanks", passer: "Grogan", rusher: "Cunningham", receiver: "Vataha", srs: -4.3 },
      { year: 1974, lg: "NFL", team: "New England Patriots", w: 7, l: 7, t: 0, finish: "3rd of 5", playoffs: "", pf: 348, pa: 289, diff: 59, coach: "Fairbanks", passer: "Plunkett", rusher: "Herron", receiver: "Vataha", srs: 4.8 },
      { year: 1973, lg: "NFL", team: "New England Patriots", w: 5, l: 9, t: 0, finish: "3rd of 5", playoffs: "", pf: 258, pa: 300, diff: -42, coach: "Fairbanks", passer: "Plunkett", rusher: "Cunningham", receiver: "Rucker", srs: -6.0 },
      { year: 1972, lg: "NFL", team: "New England Patriots", w: 3, l: 11, t: 0, finish: "5th of 5", playoffs: "", pf: 192, pa: 446, diff: -254, coach: "Mazur,Bengtson", passer: "Plunkett", rusher: "Ashton", receiver: "Rucker", srs: -17.4 },
      { year: 1971, lg: "NFL", team: "New England Patriots", w: 6, l: 8, t: 0, finish: "3rd of 5", playoffs: "", pf: 238, pa: 325, diff: -87, coach: "Mazur", passer: "Plunkett", rusher: "Garrett", receiver: "Vataha", srs: -5.1 },
      { year: 1970, lg: "NFL", team: "Boston Patriots", w: 2, l: 12, t: 0, finish: "5th of 5", playoffs: "", pf: 149, pa: 361, diff: -212, coach: "Rush,Mazur", passer: "Kapp", rusher: "Nance", receiver: "Sellers", srs: -15.9 },
      { year: 1969, lg: "AFL", team: "Boston Patriots", w: 4, l: 10, t: 0, finish: "3rd of 5", playoffs: "", pf: 266, pa: 316, diff: -50, coach: "Rush", passer: "Taliaferro", rusher: "Nance", receiver: "Sellers", srs: -4.0 },
      { year: 1968, lg: "AFL", team: "Boston Patriots", w: 4, l: 10, t: 0, finish: "4th of 5", playoffs: "", pf: 229, pa: 406, diff: -177, coach: "Holovak", passer: "Sherman", rusher: "Nance", receiver: "Whalen", srs: -12.8 },
      { year: 1967, lg: "AFL", team: "Boston Patriots", w: 3, l: 10, t: 1, finish: "5th of 5", playoffs: "", pf: 280, pa: 389, diff: -109, coach: "Holovak", passer: "Parilli", rusher: "Nance", receiver: "Whalen", srs: -6.7 },
      { year: 1966, lg: "AFL", team: "Boston Patriots", w: 8, l: 4, t: 2, finish: "2nd of 5", playoffs: "", pf: 315, pa: 283, diff: 32, coach: "Holovak", passer: "Parilli", rusher: "Nance", receiver: "Cappelletti", srs: 2.5 },
      { year: 1965, lg: "AFL", team: "Boston Patriots", w: 4, l: 8, t: 2, finish: "3rd of 4", playoffs: "", pf: 244, pa: 302, diff: -58, coach: "Holovak", passer: "Parilli", rusher: "Nance", receiver: "Cappelletti", srs: -3.6 },
      { year: 1964, lg: "AFL", team: "Boston Patriots", w: 10, l: 3, t: 1, finish: "2nd of 4", playoffs: "", pf: 365, pa: 297, diff: 68, coach: "Holovak", passer: "Parilli", rusher: "Garron", receiver: "Cappelletti", srs: 4.3 },
      { year: 1963, lg: "AFL", team: "Boston Patriots", w: 7, l: 6, t: 1, finish: "1st of 4", playoffs: "Lost Champ", pf: 327, pa: 257, diff: 70, coach: "Holovak", passer: "Parilli", rusher: "Garron", receiver: "Colclough", srs: 4.4 },
      { year: 1962, lg: "AFL", team: "Boston Patriots", w: 9, l: 4, t: 1, finish: "2nd of 4", playoffs: "", pf: 346, pa: 295, diff: 51, coach: "Holovak", passer: "Parilli", rusher: "Burton", receiver: "Colclough", srs: 3.2 },
      { year: 1961, lg: "AFL", team: "Boston Patriots", w: 9, l: 4, t: 1, finish: "2nd of 4", playoffs: "", pf: 413, pa: 313, diff: 100, coach: "Holovak,Saban", passer: "Songin", rusher: "Lott", receiver: "Cappelletti", srs: 6.3 },
      { year: 1960, lg: "AFL", team: "Boston Patriots", w: 5, l: 9, t: 0, finish: "4th of 4", playoffs: "", pf: 286, pa: 349, diff: -63, coach: "Saban", passer: "Songin", rusher: "Miller", receiver: "Colclough", srs: -3.9 },
    ],
  },

  redsox: {
    name: "Boston Red Sox",
    league: "MLB",
    color: "#0d2b56",
    accent: "#bd3039",
    logoText: "BOS",
    blurb: "AL East · Fenway Park, Boston, MA",
    // Free, official, no API key required: https://statsapi.mlb.com
    liveConfig: { provider: "mlb-stats-api", teamId: 111 },
    scores: [
      { date: "2026-08-19", opponent: "Tampa Bay Rays", home: true, result: "W", teamScore: 6, oppScore: 3, note: "" },
      { date: "2026-08-20", opponent: "Tampa Bay Rays", home: true, result: "W", teamScore: 4, oppScore: 2, note: "" },
      { date: "2026-08-21", opponent: "Tampa Bay Rays", home: true, result: "L", teamScore: 1, oppScore: 5, note: "" },
      { date: "2026-08-23", opponent: "New York Yankees", home: false, result: "W", teamScore: 7, oppScore: 4, note: "" },
      { date: "2026-08-24", opponent: "New York Yankees", home: false, result: "L", teamScore: 2, oppScore: 3, note: "10 innings" },
    ],
    schedule: [
      { date: "2026-08-25", opponent: "New York Yankees", home: false, time: "1:35 PM" },
      { date: "2026-08-26", opponent: "Baltimore Orioles", home: true, time: "7:10 PM" },
      { date: "2026-08-27", opponent: "Baltimore Orioles", home: true, time: "7:10 PM" },
      { date: "2026-08-28", opponent: "Baltimore Orioles", home: true, time: "1:35 PM" },
      { date: "2026-08-29", opponent: "Toronto Blue Jays", home: false, time: "7:07 PM" },
      { date: "2026-08-30", opponent: "Toronto Blue Jays", home: false, time: "3:07 PM" },
    ],
    standings: {
      group: "AL East",
      rows: [
        { team: "New York Yankees", w: 75, l: 55, pct: ".577", gb: "-" },
        { team: "Boston Red Sox", w: 71, l: 58, pct: ".550", gb: "3.5" },
        { team: "Baltimore Orioles", w: 68, l: 61, pct: ".527", gb: "6.5" },
        { team: "Tampa Bay Rays", w: 63, l: 66, pct: ".488", gb: "11.5" },
        { team: "Toronto Blue Jays", w: 60, l: 69, pct: ".465", gb: "14.5" },
      ],
      note: "Standings as of Aug 25, 2026",
    },
    players: [
      { name: "Rafael Devers", pos: "3B", statLine: ".289 AVG · 32 HR · 94 RBI · .932 OPS" },
      { name: "Jarren Duran", pos: "OF", statLine: ".278 AVG · 41 SB · 12 HR · .811 OPS" },
      { name: "Triston Casas", pos: "1B", statLine: ".251 AVG · 24 HR · 71 RBI · .845 OPS" },
      { name: "Ceddanne Rafaela", pos: "SS", statLine: ".266 AVG · 15 HR · 8 SB" },
      { name: "Brayan Bello", pos: "SP", statLine: "12-8 · 3.61 ERA · 154 K" },
      { name: "Garrett Whitlock", pos: "RP", statLine: "2.94 ERA · 21 SV · 68 K" },
    ],
  },

  celtics: {
    name: "Boston Celtics",
    league: "NBA",
    color: "#0c2340",
    accent: "#007a33",
    logoText: "BOS",
    blurb: "Eastern Conference · TD Garden, Boston, MA",
    scores: [
      { date: "2026-05-04", opponent: "New York Knicks", home: true, result: "W", teamScore: 112, oppScore: 98, note: "Playoffs R2 G1" },
      { date: "2026-05-06", opponent: "New York Knicks", home: true, result: "W", teamScore: 105, oppScore: 101, note: "Playoffs R2 G2" },
      { date: "2026-05-09", opponent: "New York Knicks", home: false, result: "L", teamScore: 94, oppScore: 108, note: "Playoffs R2 G3" },
      { date: "2026-05-11", opponent: "New York Knicks", home: false, result: "W", teamScore: 117, oppScore: 110, note: "Playoffs R2 G4" },
      { date: "2026-05-13", opponent: "New York Knicks", home: true, result: "W", teamScore: 121, oppScore: 103, note: "Playoffs R2 G5 - Series clinched" },
    ],
    schedule: [
      { date: "2026-10-22", opponent: "New York Knicks", home: true, time: "7:30 PM", note: "Season Opener" },
      { date: "2026-10-24", opponent: "Washington Wizards", home: false, time: "7:00 PM" },
      { date: "2026-10-26", opponent: "Miami Heat", home: true, time: "6:00 PM" },
      { date: "2026-10-29", opponent: "Philadelphia 76ers", home: true, time: "7:30 PM" },
      { date: "2026-10-31", opponent: "Milwaukee Bucks", home: false, time: "8:00 PM" },
      { date: "2026-11-02", opponent: "Cleveland Cavaliers", home: false, time: "6:00 PM" },
    ],
    standings: {
      group: "Eastern Conference",
      rows: [
        { team: "Boston Celtics", w: 58, l: 24, pct: ".707", gb: "-" },
        { team: "Cleveland Cavaliers", w: 55, l: 27, pct: ".671", gb: "3.0" },
        { team: "New York Knicks", w: 52, l: 30, pct: ".634", gb: "6.0" },
        { team: "Milwaukee Bucks", w: 47, l: 35, pct: ".573", gb: "11.0" },
        { team: "Philadelphia 76ers", w: 44, l: 38, pct: ".537", gb: "14.0" },
      ],
      note: "Final 2025-26 regular-season standings (most recent completed NBA season)",
    },
    players: [
      { name: "Jayson Tatum", pos: "F", statLine: "27.8 PPG · 8.4 RPG · 4.9 APG" },
      { name: "Jaylen Brown", pos: "G/F", statLine: "23.6 PPG · 5.5 RPG · 3.6 APG" },
      { name: "Derrick White", pos: "G", statLine: "16.2 PPG · 4.1 APG · 1.4 SPG" },
      { name: "Kristaps Porzingis", pos: "C", statLine: "19.4 PPG · 7.1 RPG · 1.9 BPG" },
      { name: "Jrue Holiday", pos: "G", statLine: "12.9 PPG · 4.8 APG · 1.1 SPG" },
      { name: "Payton Pritchard", pos: "G", statLine: "14.3 PPG · 3.7 APG · 41% 3PT" },
    ],
  },
};
